### ISSUE TITLE
push_to_gh.sh is broken

### ISSUE THREAD

**Issue by fdhadzh** [pre-commit/pre-commit.github.io#106]
![2017-04-13 22 09 10](https://cloud.githubusercontent.com/assets/6820504/25020136/dcb65fd2-2095-11e7-843c-9fe8db2758c7.png)

**Comment by asottile** [comment]
Indeed it is.  My guess would be @struys changed his push key.  I'll put mine in place instead (and use a newer version of this script I've written: https://github.com/anthonywritescode/markdown-to-presentation#hooking-up-push-to-github-pages

**Comment by asottile** [comment]
@fdhadzh thanks for the report! I'm sad and surprised I didn't notice earlier!

**Comment by fdhadzh** [comment]
@asottile my pleasure.
