### ISSUE TITLE
Project name is very hard to google

### ISSUE THREAD

**Issue by yourcelf** [pre-commit/pre-commit.github.io#184]
It may be a bit late for a change, but I wanted to point out that as someone getting started with pre-commit, the project name is very hard to use.

Since `pre-commit` is the name of the git feature that this framework exercises, most searches for "pre-commit" will only return references to the underlying git feature, and not this framework.  In particular, this makes it hard to find example configuration files, or other peoples' plugins that are designed to provide hooks for the framework.  It's hard to even talk to the uninitiated in e.g. a blog post -- "I'm using pre-commit to manage pre-commit hooks, and here's why it's great."

Other projects have faced this issue and developed conventions for talking about the project online (e.g. "golang" for "go").  I don't know if it's possible to come up with some convention like that to make references to the project more semantically unique.

Opening this as a "pre-commit.com" issue, since it seems that the public facing website for the project is the place that would suggest and promote such a convention if one could be found.

**Comment by asottile** [comment]
Yeah a bit unfortunate, it's a little too late to rename at this point :(

It is cumbersome but I often refer to it as "pre-commit the framework"

That said, the SEO is pretty strong so even just "pre-commit" works (private tab):

![screenshot from 2018-09-27 16-45-01](https://user-images.githubusercontent.com/1810591/46180346-b4327280-c274-11e8-95a2-4b3e68d97638.png)
