### ISSUE TITLE
Don't suggest running get-pip.py with sudo

### ISSUE THREAD

**Issue by pradyunsg** [pre-commit/pre-commit.github.io#190]
The regular caveats of running pip with sudo apply, including (but not limited to) breaking the user's installation of pip.

https://stackoverflow.com/a/37104948/1931274

**Comment by asottile** [comment]
yeah, I feel you :/  -- it was added in haste and to be honest for users that don't use / understand the python ecosystem (and may or may not have `pip` available).

I'm ok with just deleting that section entirely -- would you like to make a PR?

**Comment by asottile** [comment]
Here's where that lives by the way:

https://github.com/pre-commit/pre-commit.github.io/blob/40904af80edc0ae37bf8c62b608323285b75b994/index.mako#L73-L77

**Comment by asottile** [comment]
@pradyunsg ping!
