### ISSUE TITLE
pre-commit repo badge

### ISSUE THREAD

**Issue by Kilo59** [pre-commit/pre-commit.github.io#194]
pre-commit should have its own badge with the pre-commit logo.

## Badge creation libraries
https://github.com/badges/shields
https://github.com/google/pybadges

I'm happy to create a few. 
My main questions would be, does `pre-commit` "host" it? 
Should I use the `pybadges` library and commit the code for generating badges to this repo?

**Comment by asottile** [comment]
moved!  looking forward to what you come up with :)

**Comment by sloria** [comment]
I can recommend badgen (https://github.com/amio/badgen-service) for creating custom badges. I've switched all my projects from shields/rtd/badge.fury to using the hosted badgen badges. Also, Dependabot now uses badgen to generate its badges, fwiw.

**Comment by asottile** [comment]
so a badge was added in #300 -- just need to document it

**Comment by asottile** [comment]
via #301 -- thanks again @ddelange :tada:
