### ISSUE TITLE
Clarify meaning of "hook environments"

### ISSUE THREAD

**Issue by esciara** [pre-commit/pre-commit.github.io#239]
In sections [pre-commit install](https://pre-commit.com/#pre-commit-install) and [pre-commit install-hooks](https://pre-commit.com/#pre-commit-install-hooks) are mentioned "hook environments"... Not sure what this means... Could you clarify?

Could not test what result it bring as `pre-commit install --install-hooks` only returns `pre-commit installed at .git/hooks/pre-commit` as message...

**Comment by asottile** [comment]
that means they're already up to date and installed then (it's idempotent).

here's some output you might see if they weren't already installed:

```console
$ pre-commit install --install-hooks
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

**Comment by esciara** [comment]
Thanks... can you clarify what you mean by "environment"? Is that the language?

**Comment by esciara** [comment]
or virtual environment?

**Comment by asottile** [comment]
It depends on the language, for python it's virtualenvs, for go it's a binary built from a temporary gopath. It's kind of inventing ambiguous in the docs so it doesn't need to enumerate the many different types of installs that can occur.

**Comment by esciara** [comment]
OK. Need to have a look into it and maybe quickly update the doc...

**Comment by rpdelaney** [comment]
@asottile 

> It's kind of intentionally ambiguous in the docs so it doesn't need to enumerate the many different types of installs that can occur.

Is that in the interest of saving space in the top-level documentation, or not having to maintain documentation of a moving target?

**Comment by asottile** [comment]
It's because it would be duplicated with the language-specific docs and prohibitively verbose and unnecessary to enumerate

**Comment by rpdelaney** [comment]
Gotcha. Well, I understand the problem, but I'd gently suggest that directing the reader to the language specific docs would be better than intentional vagueness in this case.

**Comment by asottile** [comment]
patches welcome!
