### ISSUE TITLE
Add relint to supported hooks, please

### ISSUE THREAD

**Issue by moseb** [pre-commit/pre-commit.github.io#252]
https://github.com/codingjoe/relint
https://github.com/codingjoe/relint/blob/master/.pre-commit-hooks.yaml

Thanks!

CC @codingjoe

**Comment by asottile** [comment]
thanks for the issue! :tada:

**Comment by moseb** [comment]
Cool!

**Comment by codingjoe** [comment]
Thanks @moseb :)
