### ISSUE TITLE
Understanding `install` vs `install --install-hooks`

### ISSUE THREAD

**Issue by rpdelaney** [pre-commit/pre-commit.github.io#255]
> * `pre-commit install`: default install invocation will run existing hook scripts alongside pre-commit.
> * `pre-commit install -f --install-hooks`: idempotently replace git hook scripts with pre-commit and also install hooks.

I'm having difficulty assuring myself that I'm parsing this correctly. Possibly related to #239. The addition of `-f` in the second example is notably unhelpful when trying to use this example to understand the contrast between `install` vs `install --install-hooks`. The docs for `-f` say it will "overwrite existing hooks / remove migration mode", which (plus the convention of what `-f` means in general) suggests that any operation with this switch should _not_ be idempotent.

Could someone help explain the difference in more detail?

There's also this:

```
$ pre-commit --help install
usage: pre-commit [-h] [-V]
                  {autoupdate,clean,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,help}
[...]
    install             Install the pre-commit script.
    install-hooks       Install hook environments for all environments in the
                        config file. You may find `pre-commit install
                        --install-hooks` more useful.
```
When would I find it more useful? Always? Should I consider `install --install-hooks` the default for initial setup?

**Comment by asottile** [comment]
Let me try and make a grid, but in list form of the possible commands / situations:

- `pre-commit install`
    - :heavy_check_mark: installs `.git/hooks/pre-commit`
    - :heavy_check_mark: keeps non-pre-commit hooks around (`.git/hooks/pre-commit.legacy` -- migration mode)
    - :x: installs hook environments
    - :heavy_check_mark: idempotent
- `pre-commit install-hooks`
    - :x: installs `.git/hooks/pre-commit`
    - :x: keeps non-pre-commit hooks around (`.git/hooks/pre-commit.legacy` -- migration mode)
    - :heavy_check_mark: installs hook environments
    - :heavy_check_mark: idempotent
- `pre-commit install --install-hooks`
    - :heavy_check_mark: installs `.git/hooks/pre-commit`
    - :heavy_check_mark: keeps non-pre-commit hooks around (`.git/hooks/pre-commit.legacy` -- migration mode)
    - :heavy_check_mark: installs hook environments
    - :heavy_check_mark: idempotent
- `pre-commit install --install-hooks --force`
    - :heavy_check_mark: installs `.git/hooks/pre-commit`
    - :x: keeps non-pre-commit hooks around (`.git/hooks/pre-commit.legacy` -- migration mode)
    - :heavy_check_mark: installs hook environments
    - :heavy_check_mark: idempotent

Basically, the only time you'd care about `--install-hooks` is if you want to eagerly install the hook environments before running -- it won't really make a difference but can help improve the perception that "pre-commit is slow" by frontloading the one-time install.

`--force` isn't really a necessary option unless you were previously using some other git hooks framework and want to no longer use that framework.  ~technically all of the operations are idempotent but in the case of `--force` it's called out explicitly (similar to the way that `rm -f` and `mkdir -p` are idempotent)

The reason the full command is shown is that was the most common invocation at yelp where they were migrating from a 2k line bash-based git hooks framework and wanted `make minimal` to eagerly install the hook environments

**Comment by rpdelaney** [comment]
Thank you! That's very clear and helpful.

If it would help integrate that into the docs, I could built out a markdown table or such, or just send a PR if you would accept it.

**Comment by asottile** [comment]
I don't think it's necessary at all, each of the options are independent and already documented -- if there's clarification needed for the individual options I'd suggest augmenting those

**Comment by rpdelaney** [comment]
Where do the hook environments get installed?

**Comment by asottile** [comment]
that's implementation detail -- but `${PRE_COMMIT_HOME:-${XDG_CACHE_HOME:-~/.cache}/pre-commit}/...`

**Comment by rpdelaney** [comment]
Cool, thanks. Yeah, don't intend to document this explicitly, just testing some behavior to make sure I get a couple things right.

**Comment by tolomea** [comment]
The bit that always confuses me about this is I think of `.git/hooks/pre-commit` as a `hook` so my mind assumes `install-hooks` is creating that. It all makes sense once you realize `hooks` here means the venvs for the linters etc. 

I get how it's rooted in the origins of pre-commit and it's probably too late to change. But calling the things it runs tools instead of hooks might've made some things clearer.
