### ISSUE TITLE
copyable code blocks for badges

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit.github.io#330]
it would be nice to be able to copy and paste the code with a button or auto-select the code when clicking

**Comment by ammarnajjar** [comment]
May I give this a shot? :)

**Comment by asottile** [comment]
sure!

**Comment by ammarnajjar** [comment]
@asottile , I thought that it might be a good idea to be able to copy any code block on the page, not just the badging section, so please give your take on the open PR #331. 
To make review easier, I made it of two commits: before and after javascript minification.
