### ISSUE TITLE
Allow setting of PRE_COMMIT_HOME in configuration file

### ISSUE THREAD

**Issue by paddy-hack** [pre-commit/pre-commit.github.io#354]
Looking for a GitLab CI snippet, I stumbled upon #343 and wondered why the cache directory cannot be set in the `.pre-commit-config.yaml` file or even default to the current project's top-level directory.  Environment variables could be used to override that if desired.

My thinking behind this is that I might have multiple projects using `pre-commit` with wildly different repo versions.  Now, imagine running `pre-commit gc` in one project wiping repos that are used by another project.  I don't know if/how `pre-commit` handles this under the covers, but I think keeping project specific things within each project's checkout would solve this.

Putting everything in a project's `.cache/` by default and allowing project's to set a different value in their `.pre-commit-config.yaml` would nicely solve this and make dealing with caches during CI a bit easier to deal with too.

**Comment by asottile** [comment]
because the point of the cache is it is shared, there is nothing project specific about the things installed into it

your assumption about `pre-commit gc` is entirely wrong, pre-commit keeps track of the repositories on disk that are using pre-commit and will not purge in-use repositories.  the problem you're describing simply does not exist

**Comment by asottile** [comment]
I will not add a configuration value for something which is against the design of the project

**Comment by paddy-hack** [comment]
Your prerogative :grin:  
I'm just getting started with pre-commit and this seemed like something that might break things to me.  Sorry for not immediately grasping what is going on underneath the covers.  :bow:

**Comment by paddy-hack** [comment]
> your assumption about pre-commit gc is entirely wrong, pre-commit keeps track of the repositories on disk that are using pre-commit and will not purge in-use repositories. the problem you're describing simply does not exist

Question.  Does it also take versions of repositories into account?

**Comment by asottile** [comment]
yes and it's very easy to validate by trying it

**Comment by paddy-hack** [comment]
Thanks.  I just confirmed that it did, at least for the limited test I performed.

**Comment by woutervh** [comment]
@asottile 

I understand your points about the project-agnostic cache.

> because the point of the cache is it is shared, there is nothing project specific about the things installed into it

This is an argument against a *value* some people want to set for PRE_COMMIT_HOME.
I just want to set it outside of a users $HOME, depending on the use case.

so it's annoying not to be able to do that inside the config-file, and force people to manage an extra layer of config.
Can you re-consider this?
