### ISSUE TITLE
Split up the doc pages

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit.github.io#49]
I've been wanting to do this for a while since the homepage is getting pretty long.

Basically what I want the homepage to be is a quickstart guide and have there be separate pages that go more in-depth

**Comment by struys** [comment]
Sounds good to me. A few nice to haves:
- A gif/video that shows how pre-commit works
- Since we're splitting up into pages, search with ctrl+f won't work anymore, maybe add this? - https://cse.google.com/cse/

**Comment by asottile** [comment]
I'd also like to incorporate #29 into this, or just inline examples

**Comment by awebdeveloper** [comment]
Also the hooks should be sorted by language too.

**Comment by asottile** [comment]
I'm not actually going to split up the pages, breaking existing links and ^F seems not a good idea.

**Comment by awebdeveloper** [comment]
if your referring to # links then you can still tag the quick  links with id which will not break the old link
