### ISSUE TITLE
Document "local" hooks

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit.github.io#50]
@Lucas-C either I can get to this or you can take a first stab

**Comment by Lucas-C** [comment]
It was on top of my todo-list :) But I won't find time for it before next week so it's up to you.
I also have a suggestion: I think it'd be good to include on the homepage a screenshot of `pre-commit` command output.
A bit like this but with all the possible outcome possibilities (i.e. skipped, failed)
![](https://cloud.githubusercontent.com/assets/925560/7714051/f9044af2-fe7b-11e4-949b-6cf0fe53e994.png)

**Comment by asottile** [comment]
++ Yeah I plan to add that with fixups in #49

**Comment by Lucas-C** [comment]
Here is a more complete screenshot. Feel free to use it if you like it.
![pre-commit](https://cloud.githubusercontent.com/assets/925560/9099979/13bae3c8-3bd6-11e5-8e35-96fa57f2e4ba.png)

**Comment by asottile** [comment]
I threw these together as well a while back: ![](https://raw.githubusercontent.com/pre-commit/pre-commit.github.io/better_docs/pre-push.gif) ![](https://raw.githubusercontent.com/pre-commit/pre-commit.github.io/better_docs/pre-commit.gif)

in this branch: https://github.com/pre-commit/pre-commit.github.io/tree/better_docs

I just haven't gotten around to finishing it (so busy!)

**Comment by Lucas-C** [comment]
Awesome !
Looks really promising :)

**Comment by asottile** [comment]
@Lucas-C want to take a first stab at this one or should I write up a blurb?

**Comment by Lucas-C** [comment]
No, go ahead !

**Comment by asottile** [comment]
This is now implemented! http://pre-commit.com/#repository-local-hooks
